- name: Ensure the accounts partition is unmounted
  become: true
  shell: umount /dev/{{ accounts_disk }}p1 || true

- name: Ensure the ledger partition is unmounted
  become: true
  shell: umount /dev/{{ ledger_disk }}p1 || true

- name: Check if ledger disk is already mounted
  become: true
  command: mountpoint -q /mnt/solana-ledger
  ignore_errors: true
  register: mount_ledger

- name: Check if accounts disk is already mounted
  become: true
  command: mountpoint -q /mnt/solana-accounts
  ignore_errors: true
  register: mount_accounts

- name: Create a partition on the accounts disk
  become: true
  command: parted /dev/{{ accounts_disk }} --script mklabel gpt mkpart primary ext4 0% 100%
  when: mount_accounts.rc != 0

- name: Create a partition on the ledger disk
  become: true
  command: parted /dev/{{ ledger_disk }} --script mklabel gpt mkpart primary ext4 0% 100%
  when: mount_ledger.rc != 0

- name: Format accounts partition with ext4
  become: true
  filesystem:
    fstype: ext4
    dev: /dev/{{ accounts_disk }}p1
  when: mount_accounts.rc != 0

- name: Format ledger partition with ext4
  become: true
  filesystem:
    fstype: ext4
    dev: /dev/{{ ledger_disk }}p1
  when: mount_ledger.rc != 0

- name: Create mount point for accounts disk
  become: true
  file:
    path: /mnt/solana-accounts
    state: directory
  when: mount_accounts.rc != 0

- name: Create mount point for ledger disk
  become: true
  file:
    path: /mnt/solana-ledger
    state: directory
  when: mount_ledger.rc != 0

- name: Mount accounts disk
  become: true
  mount:
    path: /mnt/solana-accounts
    src: /dev/{{ accounts_disk }}p1
    fstype: ext4
    state: mounted
  when: mount_accounts.rc != 0

- name: Mount ledger disk
  become: true
  mount:
    path: /mnt/solana-ledger
    src: /dev/{{ ledger_disk }}p1
    fstype: ext4
    state: mounted
  when: mount_ledger.rc != 0

- name: Add accounts disk to fstab
  become: true
  mount:
    path: /mnt/solana-accounts
    src: /dev/{{ accounts_disk }}p1
    fstype: ext4
    opts: defaults
    state: present

- name: Add ledger disk to fstab
  become: true
  mount:
    path: /mnt/solana-ledger
    src: /dev/{{ ledger_disk }}p1
    fstype: ext4
    opts: defaults
    state: present
