- name: check mount
  become: true
  become_user: root
  shell: df -h | grep mnt/solana-ledger
  ignore_errors: yes
  register: mount_mnt

- name: format ledger disk with ext4
  become: true
  become_user: root
  shell: mkfs.ext4 /dev/{{ ledger_disk }}
  when: mount_mnt.rc != 0

- name: format snapshots disk with ext4
  become: true
  become_user: root
  shell: mkfs.ext4 /dev/{{ snapshots_disk }}
  when: mount_mnt.rc != 0

- name: mount disks for accounts
  become: true
  become_user: root
  shell: mount /dev/{{ ledger_disk }} /mnt/solana-ledger && chown -R solana:solana /mnt/solana-ledger
  when: mount_mnt.rc != 0

- name: mount disks for snapshots
  become: true
  become_user: root
  shell: mount /dev/{{ snapshots_disk }} /mnt/solana-snapshots && chown -R solana:solana /mnt/solana-snapshots
  when: mount_mnt.rc != 0

- name: add ledger disk to fstab
  become: true
  become_user: root
  lineinfile:
    dest: /etc/fstab
    state: present
    line: "/dev/{{ ledger_disk }}    /mnt/solana-ledger    ext4    defaults    0    1"

- name: add snapshots disk to fstab
  become: true
  become_user: root
  lineinfile:
    dest: /etc/fstab
    state: present
    line: "/dev/{{ snapshots_disk }}    /mnt/solana-snapshots    ext4    defaults    0    1"
